export const FETCH_COUNTRY_INFO = "FETCH_COUNTRY_INFO";
export const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA";
export const SORTED_CASES = "SORTED_CASES";
export const SORTED_DEATHS = "SORTED_DEATHS";
export const SORTED_RECOVERED = "SORTED_RECOVERED";
export const COUNTRIES = "COUNTRIES";
export const MAP_COUNTRIES = "MAP_COUNTRIES";
