const FETCH_COUNTRY_INFO = "FETCH_COUNTRY_INFO";
const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA";
const COUNTRY_INFO = "COUNTRY_INFO";
const COUNTRY_INFO = "COUNTRY_INFO";
const COUNTRY_INFO = "COUNTRY_INFO";
